name: build-test-lint
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  build-test-lint:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: 22
    - run: npm ci
    - run: npm test