name: build-test-lint
on:
  push:
    branches:
      - main
  on:
    pull_request:
      types: [opened, reopened]


jobs:
  build-test-lint:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: 22
    - run: npm ci
    - run: npm test