/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: cattleya (https://sketchfab.com/cattleya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-treasure-chest-ca63751326084866b8df9a6b4c196b3d
Title: Low poly treasure chest
*/

import React, {useEffect, useState} from 'react'
import {Outlines, useGLTF} from '@react-three/drei'
import {useNavigate} from "react-router-dom";

const model_url = "https://dustin-alandzes-personal.s3.us-east-1.amazonaws.com/multiverse/chest.glb"

export default function Model(props) {
    const { nodes, materials } = useGLTF(model_url)
    const navigate = useNavigate();

    const [hovered, setHovered] = useState(false)

    useEffect(() => {
        document.body.style.cursor = hovered ? 'pointer' : 'auto'
    }, [hovered])

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow={true}
                    receiveShadow={true}
                    geometry={nodes.Box001_chest_0.geometry}
                    material={materials.chest}
                    position={[-11.493, -42.675, 0]}
                    onPointerOver={() => setHovered(true)}
                    onPointerOut={() => setHovered(false)}
                    onClick={() => navigate("/")}
                >
                    {hovered && <Outlines thickness={2} color="black" />}
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload(model_url)